blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
# urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # urls address, view function name, and name for write in HTML code section
    # Home page
    path('', views.index, name='index'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    path('posts/<int:post_id>/', views.post, name='post'),
    path('new_blog/', views.new_blog, name='new_blog'),
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
# urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    """A blog type the user writing."""
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Post(models.Model):
    """Posts that are in each blog."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string of model instead of entire model."""
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
# forms.py
from django import forms

from .models import Blog, Post

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title']
        labels = {'title': ''}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']
        labels = {'title': 'Subject:', 'text': 'Content:'}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Post
from .forms import BlogForm, PostForm
# Create your views here.
# redirect want a view argument, request want a template html argument

def check_owner(user, request):
    if user.owner != request.user:
        raise Http404

def index(request):
    """Home page for Blog"""
    return render(request, 'blogs/index.html') # original request and a template

@login_required
def blogs(request):
    """A page show all blogs."""
    blogs = Blog.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

@login_required
def blog(request, blog_id):
    """A page for each blog"""
    blog = get_object_or_404(Blog, id=blog_id)
    check_owner(blog, request)
    posts = blog.post_set.order_by('-date_added')
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

@login_required
def post(request, post_id):
    """A post in the blog."""
    post = get_object_or_404(Post, id=post_id)
    blog = post.blog
    check_owner(blog, request)
    context = {'post': post, 'blog': blog}
    return render(request, 'blogs/post.html', context)

@login_required
def new_blog(request):
    """Add a new blog"""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect('blogs:blogs')
# Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)
# render code will be execute for a blank form or invalid submitted form only.

@login_required
def new_post(request, blog_id):
    """Add a post into the blog"""
    blog = get_object_or_404(Blog, id=blog_id)

    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

# Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    blog = post.blog
    check_owner(blog, request)

    if request.method != 'POST':
    # This is an existing post, so I'll put an existing form
        form = PostForm(instance=post)
    else:
        # POST data submitted; after edited data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post_id)

    context = {'post': post, 'blog': blog, 'form':form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
# Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

# Create your views here.

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, 
    initial-scale=1, shrink-to-fit=no">
  <title>Blog for Everyone</title>
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'blogs:index' %}">Home</a>
    <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'blogs:blogs' %}">Blogs</a></li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
	{% else %}
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
	{% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h3>{{ blog }}</h3>
{% endblock page_header %}

{% block content %}
  <p></p>
  <h5><a href="{% url 'blogs:new_post' blog.id %}">Add post</a></h5>
  <p></p>
    {% for post in posts %}
      <div class="card mb-3">
        <h5 class="card-header">
          <a href="{% url 'blogs:post' post.id %}">{{ post.title.capitalize }}</a>
          <p><small class="text-muted">{{ post.date_added|date:'d M, Y H:i' }}</small></p>
        </h5>
      </div>
    {% empty %}
      <p>There has no post in this blog yet.</p>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}
{% block page_header %}
  <h1>Blogs</h1>
{% endblock page_header %}

{% block content %}
    <ul>
      {% for blog in blogs %}
        <li><h4>
          <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}
        </h4></li>
      {% empty %}
        <li><h4>There is no blog yet.</h4></li>
      {% endfor %}
    </ul>
  <h5><a href="{% url 'blogs:new_blog' %}">Add blog</a></h5>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3 class="lead"><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></h3>
  <h3>Edit Post: <a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h3>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:edit_post' post.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button name="submit" class="btn btn-primary">Save changes</button>
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

  {% block page_header %}
    <div class="jumbotron">

      <h1 class="display-3">Make your own space.</h1>

      <p class="lead">Make your own Blog, create your comfort zone. Post your progression whenever you want.</p>

      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>

    </div>

{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3>Add a new blog</h3>
{% endblock page_header %}

{% block content %}
  <p></p>
  <form method='post' action="{% url 'blogs:new_blog' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-outline-primary">Add blog</button>
    {% endbuttons %}
  </form>


{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h3 class="lead"><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></h3>
<h3>Add a new post</h3>
{% endblock page_header %}

{% block content %}
  <p></p>

  <form action="{% url 'blogs:new_post' blog.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button name='submit' class="btn btn-primary">Add post</button>
  </form>



{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <h6 class="lead">
    <a href="{% url 'blogs:blog' blog.id %}">{{ blog }}<a>
  </h6>
  <h3>
    <p>{{ post.title.capitalize }}</p>
  </h3>
{% endblock page_header %}

{% block content %}
  <div class="container-fluid">
    <p>{{ post.text }}</p>
    <p>{{ post.date_added|date:'d M, Y h:i' }}</p>
  </div>
 <h6><a href="{% url 'blogs:edit_post' post.id %}">Edit post</a></h6>

{% endblock content %}